# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# leave blank for localtime
# timezone =

# max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without a source .py file to be detected as revisions in the versions/ directory
# sourceless = false

# version location specification; This defaults to alembic/versions.  When using multiple version
# directories, paths must be separated by commas, which can be verbose.  Instead, specify
# names from the [post_write_hooks] section to help generate this.
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# version_path_separator = :

# set to 'true' to search source files recursively in the versions/ directory
# recursive_version_research = false

# the output encoding used when writing revision files
# output_encoding = utf-8

sqlalchemy.url = sqlite:///./sql_app.db


[post_write_hooks]
# post_write_hooks allows scripts to run after a revision file is generated.

# format using "black" - see the "black" documentation for setup;
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 (rootdir)/backend/alembic/versions/

[logging]
# logging configuration
# see https://docs.python.org/3/library/logging.config.html

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
